# The location which your server is listening on and binds to. You must restart
# bunbun for changes to take effect for this config option.
bind_address: "127.0.0.1:8080"

# The root location where people can access your instance of bunbun
public_address: "localhost:8080"

# A default route, if no route is was matched. If none were matched, the entire
# query is used as the query for the default route. This field is optional.
default_route: "g"

routes:
  # Meta
  ls: "/ls"
  help: "/ls"
  list: "/ls"
  # Google
  g: "https://google.com/search?q={{query}}"
  yt: "https://www.youtube.com/results?search_query={{query}}"
  r: "https://reddit.com/r/{{query}}"
