bind_address: "127.0.0.1:8080"
public_address: "localhost:8080"

default_route: "g"

routes:
  # Meta
  ls: "/ls"
  help: "/ls"
  list: "/ls"
  # Google
  g: "https://google.com/search?q={{query}}"
  yt: "https://www.youtube.com/results?search_query={{query}}"
  # Searches
  na: "https://nyaa.si/?f=0&c=1_2&q={{query}}"
  #
