[package]
name = "bunbun"
version = "0.7.0"
authors = ["Edward Shen <code@eddie.sh>"]
edition = "2018"
description = "Re-implementation of bunny1 in Rust"
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/edward-shen/bunbun"
exclude = ["/aux/"]

[dependencies]
actix-web = "3.0"
actix-rt = "1.1"
dirs = "3.0"
serde = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
handlebars = "3.5"
hotwatch = "0.4"
percent-encoding = "2.1"
log = "0.4"
simple_logger = "1.3"
clap = { version = "3.0.0-beta.1", features = ["wrap_help"] }

[dev-dependencies]
tempfile = "3.1"

[profile.release]
lto = true
