[package]
name = "bunbun"
version = "0.2.2"
authors = ["Edward Shen <code@eddie.sh>"]
edition = "2018"
description = "Re-implementation of bunny1 in Rust"
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/edward-shen/bunbun"

[dependencies]
actix-web = "1.0"
serde = "1.0"
serde_yaml = "0.8"
handlebars = "2.0"
hotwatch = "0.4"
percent-encoding = "2.1"
itertools = "0.8"
libc = "0.2"
log = "0.4"
simple_logger = "1.3"
clap = { version = "2.33", features = ["yaml"] }

[profile.release]
lto = true
